### ISSUE TITLE
Guid properties cause Deserialization issue using CosmosDB

### ISSUE THREAD

**Issue by matt-psaltis** [ExRam/ExRam.Gremlinq#103]
**Describe the bug**
When using CosmosDB and a Guid property on the Vertex model a deserialization exception is thrown.

**Expected behavior**
Guids and Nullable Guids should work like other types

**Version information**
8.0.0-preview-0926

**Minimal working example**
```
g.AddV(new Tester
                {
                    Id = Guid.NewGuid(),
                    Name = "OwnerTest",
                    Test = Guid.NewGuid(),
                    TenantId = "TenantTest"
                })
                .FirstOrDefaultAsync();

    class Tester : IVertex
    {
        public object? Id { get; set; }
        public string Name { get; set; }
        public string TenantId { get; set; }
        public Guid Test { get; set; }
    }

```

The exception appears to be thrown because the return object from the call to CosmosDB is a key value pair of {"id": <Guid>, "value": <Guid>}

```
Newtonsoft.Json.JsonSerializationException
Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Guid' because the type requires a JSON primitive value (e.g. string, number, boolean, null) to deserialize correctly.
To fix this error either change the JSON to a JSON primitive value (e.g. string, number, boolean, null) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path '[0].id'.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at ExRam.Gremlinq.Core.GremlinQueryExecutionResultDeserializer.<>c.<.cctor>b__11_0(JToken jToken, Type type, IGremlinQueryEnvironment env, Func`5 overridden, IGremlinQueryFragmentDeserializer recurse) in /home/runner/work/ExRam.Gremlinq/ExRam.Gremlinq/ExRam.Gremlinq.Core/Deserialization/GremlinQueryExecutionResultDeserializer.cs:line 121
   at lambda_method(Closure , JToken , Type , IGremlinQueryEnvironment , IGremlinQueryFragmentDeserializer )
   at ExRam.Gremlinq.Core.GremlinQueryExecutionResultDeserializer.<>c.<.cctor>b__11_1(JToken jToken, Type type, IGremlinQueryEnvironment env, Func`5 overridden, IGremlinQueryFragmentDeserializer recurse) in /home/runner/work/ExRam.Gremlinq/ExRam.Gremlinq/ExRam.Gremlinq.Core/Deserialization/GremlinQueryExecutionResultDeserializer.cs:line 147
   at ExRam.Gremlinq.Core.GremlinQueryFragmentDeserializer.GremlinQueryFragmentDeserializerImpl.<>c__DisplayClass4_0`1.<Override>b__0(TSerialized fragment, Type type, IGremlinQueryEnvironment env, Func`5 baseSerializer, IGremlinQueryFragmentDeserializer recurse) in /home/runner/work/ExRam.Gremlinq/ExRam.Gremlinq/ExRam.Gremlinq.Core/Deserialization/GremlinQueryFragmentDeserializer.cs:line 33
   at lambda_method(Closure , JToken , Type , IGremlinQueryEnvironment , IGremlinQueryFragmentDeserializer )
   at ExRam.Gremlinq.Core.GremlinQueryExecutionResultDeserializer.<>c.<.cctor>b__11_2(JToken jToken, Type type, IGremlinQueryEnvironment env, Func`5 overridden, IGremlinQueryFragmentDeserializer recurse) in /home/runner/work/ExRam.Gremlinq/ExRam.Gremlinq/ExRam.Gremlinq.Core/Deserialization/GremlinQueryExecutionResultDeserializer.cs:line 151
   at ExRam.Gremlinq.Core.GremlinQueryFragmentDeserializer.GremlinQueryFragmentDeserializerImpl.<>c__DisplayClass4_0`1.<Override>b__0(TSerialized fragment, Type type, IGremlinQueryEnvironment env, Func`5 baseSerializer, IGremlinQueryFragmentDeserializer recurse) in /home/runner/work/ExRam.Gremlinq/ExRam.Gremlinq/ExRam.Gremlinq.Core/Deserialization/GremlinQueryFragmentDeserializer.cs:line 33
   at lambda_method(Closure , JObject , Type , IGremlinQueryEnvironment , IGremlinQueryFragmentDeserializer )
   at ExRam.Gremlinq.Core.GremlinQueryExecutionResultDeserializer.<>c.<.cctor>b__11_10(JObject jObject, Type type, IGremlinQueryEnvironment env, Func`5 overridden, IGremlinQueryFragmentDeserializer recurse) in /home/runner/work/ExRam.Gremlinq/ExRam.Gremlinq/ExRam.Gremlinq.Core/Deserialization/GremlinQueryExecutionResultDeserializer.cs:line 248
   at ExRam.Gremlinq.Core.GremlinQueryFragmentDeserializer.GremlinQueryFragmentDeserializerImpl.<>c__DisplayClass4_0`1.<Override>b__0(TSerialized fragment, Type type, IGremlinQueryEnvironment env, Func`5 baseSerializer, IGremlinQueryFragmentDeserializer recurse) in /home/runner/work/ExRam.Gremlinq/ExRam.Gremlinq/ExRam.Gremlinq.Core/Deserialization/GremlinQueryFragmentDeserializer.cs:line 33
   at lambda_method(Closure , JObject , Type , IGremlinQueryEnvironment , IGremlinQueryFragmentDeserializer )
   at ExRam.Gremlinq.Core.GremlinQueryExecutionResultDeserializer.<>c.<.cctor>b__11_11(JObject jObject, Type type, IGremlinQueryEnvironment env, Func`5 overridden, IGremlinQueryFragmentDeserializer recurse) in /home/runner/work/ExRam.Gremlinq/ExRam.Gremlinq/ExRam.Gremlinq.Core/Deserialization/GremlinQueryExecutionResultDeserializer.cs:line 261
   at ExRam.Gremlinq.Core.GremlinQueryFragmentDeserializer.GremlinQueryFragmentDeserializerImpl.<>c__DisplayClass4_0`1.<Override>b__0(TSerialized fragment, Type type, IGremlinQueryEnvironment env, Func`5 baseSerializer, IGremlinQueryFragmentDeserializer recurse) in /home/runner/work/ExRam.Gremlinq/ExRam.Gremlinq/ExRam.Gremlinq.Core/Deserialization/GremlinQueryFragmentDeserializer.cs:line 33
   at lambda_method(Closure , JObject , Type , IGremlinQueryEnvironment , IGremlinQueryFragmentDeserializer )
   at ExRam.Gremlinq.Core.GremlinQueryExecutionResultDeserializer.<>c.<.cctor>b__11_12(JObject jObject, Type type, IGremlinQueryEnvironment env, Func`5 overridden, IGremlinQueryFragmentDeserializer recurse) in /home/runner/work/ExRam.Gremlinq/ExRam.Gremlinq/ExRam.Gremlinq.Core/Deserialization/GremlinQueryExecutionResultDeserializer.cs:line 268
   at ExRam.Gremlinq.Core.GremlinQueryFragmentDeserializer.GremlinQueryFragmentDeserializerImpl.<>c__DisplayClass4_0`1.<Override>b__0(TSerialized fragment, Type type, IGremlinQueryEnvironment env, Func`5 baseSerializer, IGremlinQueryFragmentDeserializer recurse) in /home/runner/work/ExRam.Gremlinq/ExRam.Gremlinq/ExRam.Gremlinq.Core/Deserialization/GremlinQueryFragmentDeserializer.cs:line 33
   at lambda_method(Closure , JObject , Type , IGremlinQueryEnvironment , IGremlinQueryFragmentDeserializer )
   at ExRam.Gremlinq.Core.GremlinQueryExecutionResultDeserializer.<>c.<.cctor>b__11_13(JObject jObject, Type type, IGremlinQueryEnvironment env, Func`5 overridden, IGremlinQueryFragmentDeserializer recurse) in /home/runner/work/ExRam.Gremlinq/ExRam.Gremlinq/ExRam.Gremlinq.Core/Deserialization/GremlinQueryExecutionResultDeserializer.cs:line 273
   at ExRam.Gremlinq.Core.GremlinQueryFragmentDeserializer.GremlinQueryFragmentDeserializerImpl.<>c__DisplayClass4_0`1.<Override>b__0(TSerialized fragment, Type type, IGremlinQueryEnvironment env, Func`5 baseSerializer, IGremlinQueryFragmentDeserializer recurse) in /home/runner/work/ExRam.Gremlinq/ExRam.Gremlinq/ExRam.Gremlinq.Core/Deserialization/GremlinQueryFragmentDeserializer.cs:line 33
   at lambda_method(Closure , JObject , Type , IGremlinQueryEnvironment , IGremlinQueryFragmentDeserializer )
   at ExRam.Gremlinq.Core.GremlinQueryExecutionResultDeserializer.<>c.<.cctor>b__11_14(JObject jObject, Type type, IGremlinQueryEnvironment env, Func`5 overridden, IGremlinQueryFragmentDeserializer recurse) in /home/runner/work/ExRam.Gremlinq/ExRam.Gremlinq/ExRam.Gremlinq.Core/Deserialization/GremlinQueryExecutionResultDeserializer.cs:line 305
   at ExRam.Gremlinq.Core.GremlinQueryFragmentDeserializer.GremlinQueryFragmentDeserializerImpl.<>c__DisplayClass4_0`1.<Override>b__0(TSerialized fragment, Type type, IGremlinQueryEnvironment env, Func`5 baseSerializer, IGremlinQueryFragmentDeserializer recurse) in /home/runner/work/ExRam.Gremlinq/ExRam.Gremlinq/ExRam.Gremlinq.Core/Deserialization/GremlinQueryFragmentDeserializer.cs:line 33
   at lambda_method(Closure , JToken , Type , IGremlinQueryEnvironment , IGremlinQueryFragmentDeserializer )
   at ExRam.Gremlinq.Core.GremlinQueryFragmentDeserializer.GremlinQueryFragmentDeserializerImpl.TryDeserialize[TSerialized](TSerialized serializedData, Type fragmentType, IGremlinQueryEnvironment environment) in /home/runner/work/ExRam.Gremlinq/ExRam.Gremlinq/ExRam.Gremlinq.Core/Deserialization/GremlinQueryFragmentDeserializer.cs:line 22
   at ExRam.Gremlinq.Core.GremlinQueryExecutionResultDeserializer.<>c.<.cctor>b__11_15(JArray jArray, Type type, IGremlinQueryEnvironment env, Func`5 overridden, IGremlinQueryFragmentDeserializer recurse) in /home/runner/work/ExRam.Gremlinq/ExRam.Gremlinq/ExRam.Gremlinq.Core/Deserialization/GremlinQueryExecutionResultDeserializer.cs:line 318
   at ExRam.Gremlinq.Core.GremlinQueryFragmentDeserializer.GremlinQueryFragmentDeserializerImpl.<>c__DisplayClass4_0`1.<Override>b__0(TSerialized fragment, Type type, IGremlinQueryEnvironment env, Func`5 baseSerializer, IGremlinQueryFragmentDeserializer recurse) in /home/runner/work/ExRam.Gremlinq/ExRam.Gremlinq/ExRam.Gremlinq.Core/Deserialization/GremlinQueryFragmentDeserializer.cs:line 33
   at lambda_method(Closure , JArray , Type , IGremlinQueryEnvironment , IGremlinQueryFragmentDeserializer )
   at ExRam.Gremlinq.Core.GremlinQueryExecutionResultDeserializer.<>c.<.cctor>b__11_16(JArray jArray, Type type, IGremlinQueryEnvironment env, Func`5 overridden, IGremlinQueryFragmentDeserializer recurse) in /home/runner/work/ExRam.Gremlinq/ExRam.Gremlinq/ExRam.Gremlinq.Core/Deserialization/GremlinQueryExecutionResultDeserializer.cs:line 322
   at ExRam.Gremlinq.Core.GremlinQueryFragmentDeserializer.GremlinQueryFragmentDeserializerImpl.<>c__DisplayClass4_0`1.<Override>b__0(TSerialized fragment, Type type, IGremlinQueryEnvironment env, Func`5 baseSerializer, IGremlinQueryFragmentDeserializer recurse) in /home/runner/work/ExRam.Gremlinq/ExRam.Gremlinq/ExRam.Gremlinq.Core/Deserialization/GremlinQueryFragmentDeserializer.cs:line 33
   at lambda_method(Closure , JArray , Type , IGremlinQueryEnvironment , IGremlinQueryFragmentDeserializer )
   at ExRam.Gremlinq.Core.GremlinQueryExecutionResultDeserializer.<>c.<.cctor>b__11_17(JArray jArray, Type type, IGremlinQueryEnvironment env, Func`5 overridden, IGremlinQueryFragmentDeserializer recurse) in /home/runner/work/ExRam.Gremlinq/ExRam.Gremlinq/ExRam.Gremlinq.Core/Deserialization/GremlinQueryExecutionResultDeserializer.cs:line 368
   at ExRam.Gremlinq.Core.GremlinQueryFragmentDeserializer.GremlinQueryFragmentDeserializerImpl.<>c__DisplayClass4_0`1.<Override>b__0(TSerialized fragment, Type type, IGremlinQueryEnvironment env, Func`5 baseSerializer, IGremlinQueryFragmentDeserializer recurse) in /home/runner/work/ExRam.Gremlinq/ExRam.Gremlinq/ExRam.Gremlinq.Core/Deserialization/GremlinQueryFragmentDeserializer.cs:line 33
   at lambda_method(Closure , JToken , Type , IGremlinQueryEnvironment , IGremlinQueryFragmentDeserializer )
   at ExRam.Gremlinq.Core.GremlinQueryFragmentDeserializer.GremlinQueryFragmentDeserializerImpl.TryDeserialize[TSerialized](TSerialized serializedData, Type fragmentType, IGremlinQueryEnvironment environment) in /home/runner/work/ExRam.Gremlinq/ExRam.Gremlinq/ExRam.Gremlinq.Core/Deserialization/GremlinQueryFragmentDeserializer.cs:line 22
   at ExRam.Gremlinq.Core.GremlinQueryEnvironmentCache.GremlinQueryEnvironmentCacheImpl.GraphsonJsonSerializer.JTokenConverterConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in /home/runner/work/ExRam.Gremlinq/ExRam.Gremlinq/ExRam.Gremlinq.Core/Cache/GremlinQueryEnvironmentCache.cs:line 147
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at Newtonsoft.Json.JsonSerializer.PopulateInternal(JsonReader reader, Object target)
   at Newtonsoft.Json.JsonSerializer.Populate(JsonReader reader, Object target)
   at ExRam.Gremlinq.Core.GremlinQueryExecutionResultDeserializer.<>c.<.cctor>b__11_0(JToken jToken, Type type, IGremlinQueryEnvironment env, Func`5 overridden, IGremlinQueryFragmentDeserializer recurse) in /home/runner/work/ExRam.Gremlinq/ExRam.Gremlinq/ExRam.Gremlinq.Core/Deserialization/GremlinQueryExecutionResultDeserializer.cs:line 133
   at lambda_method(Closure , JToken , Type , IGremlinQueryEnvironment , IGremlinQueryFragmentDeserializer )
   at ExRam.Gremlinq.Core.GremlinQueryExecutionResultDeserializer.<>c.<.cctor>b__11_1(JToken jToken, Type type, IGremlinQueryEnvironment env, Func`5 overridden, IGremlinQueryFragmentDeserializer recurse) in /home/runner/work/ExRam.Gremlinq/ExRam.Gremlinq/ExRam.Gremlinq.Core/Deserialization/GremlinQueryExecutionResultDeserializer.cs:line 147
   at ExRam.Gremlinq.Core.GremlinQueryFragmentDeserializer.GremlinQueryFragmentDeserializerImpl.<>c__DisplayClass4_0`1.<Override>b__0(TSerialized fragment, Type type, IGremlinQueryEnvironment env, Func`5 baseSerializer, IGremlinQueryFragmentDeserializer recurse) in /home/runner/work/ExRam.Gremlinq/ExRam.Gremlinq/ExRam.Gremlinq.Core/Deserialization/GremlinQueryFragmentDeserializer.cs:line 33
   at lambda_method(Closure , JToken , Type , IGremlinQueryEnvironment , IGremlinQueryFragmentDeserializer )
   at ExRam.Gremlinq.Core.GremlinQueryExecutionResultDeserializer.<>c.<.cctor>b__11_2(JToken jToken, Type type, IGremlinQueryEnvironment env, Func`5 overridden, IGremlinQueryFragmentDeserializer recurse) in /home/runner/work/ExRam.Gremlinq/ExRam.Gremlinq/ExRam.Gremlinq.Core/Deserialization/GremlinQueryExecutionResultDeserializer.cs:line 151
   at ExRam.Gremlinq.Core.GremlinQueryFragmentDeserializer.GremlinQueryFragmentDeserializerImpl.<>c__DisplayClass4_0`1.<Override>b__0(TSerialized fragment, Type type, IGremlinQueryEnvironment env, Func`5 baseSerializer, IGremlinQueryFragmentDeserializer recurse) in /home/runner/work/ExRam.Gremlinq/ExRam.Gremlinq/ExRam.Gremlinq.Core/Deserialization/GremlinQueryFragmentDeserializer.cs:line 33
   at lambda_method(Closure , JObject , Type , IGremlinQueryEnvironment , IGremlinQueryFragmentDeserializer )
   at ExRam.Gremlinq.Core.GremlinQueryExecutionResultDeserializer.<>c.<.cctor>b__11_10(JObject jObject, Type type, IGremlinQueryEnvironment env, Func`5 overridden, IGremlinQueryFragmentDeserializer recurse) in /home/runner/work/ExRam.Gremlinq/ExRam.Gremlinq/ExRam.Gremlinq.Core/Deserialization/GremlinQueryExecutionResultDeserializer.cs:line 248
   at ExRam.Gremlinq.Core.GremlinQueryFragmentDeserializer.GremlinQueryFragmentDeserializerImpl.<>c__DisplayClass4_0`1.<Override>b__0(TSerialized fragment, Type type, IGremlinQueryEnvironment env, Func`5 baseSerializer, IGremlinQueryFragmentDeserializer recurse) in /home/runner/work/ExRam.Gremlinq/ExRam.Gremlinq/ExRam.Gremlinq.Core/Deserialization/GremlinQueryFragmentDeserializer.cs:line 33
   at lambda_method(Closure , JObject , Type , IGremlinQueryEnvironment , IGremlinQueryFragmentDeserializer )
   at ExRam.Gremlinq.Core.GremlinQueryExecutionResultDeserializer.<>c.<.cctor>b__11_11(JObject jObject, Type type, IGremlinQueryEnvironment env, Func`5 overridden, IGremlinQueryFragmentDeserializer recurse) in /home/runner/work/ExRam.Gremlinq/ExRam.Gremlinq/ExRam.Gremlinq.Core/Deserialization/GremlinQueryExecutionResultDeserializer.cs:line 261
   at ExRam.Gremlinq.Core.GremlinQueryFragmentDeserializer.GremlinQueryFragmentDeserializerImpl.<>c__DisplayClass4_0`1.<Override>b__0(TSerialized fragment, Type type, IGremlinQueryEnvironment env, Func`5 baseSerializer, IGremlinQueryFragmentDeserializer recurse) in /home/runner/work/ExRam.Gremlinq/ExRam.Gremlinq/ExRam.Gremlinq.Core/Deserialization/GremlinQueryFragmentDeserializer.cs:line 33
   at lambda_method(Closure , JObject , Type , IGremlinQueryEnvironment , IGremlinQueryFragmentDeserializer )
   at ExRam.Gremlinq.Core.GremlinQueryExecutionResultDeserializer.<>c.<.cctor>b__11_12(JObject jObject, Type type, IGremlinQueryEnvironment env, Func`5 overridden, IGremlinQueryFragmentDeserializer recurse) in /home/runner/work/ExRam.Gremlinq/ExRam.Gremlinq/ExRam.Gremlinq.Core/Deserialization/GremlinQueryExecutionResultDeserializer.cs:line 268
   at ExRam.Gremlinq.Core.GremlinQueryFragmentDeserializer.GremlinQueryFragmentDeserializerImpl.<>c__DisplayClass4_0`1.<Override>b__0(TSerialized fragment, Type type, IGremlinQueryEnvironment env, Func`5 baseSerializer, IGremlinQueryFragmentDeserializer recurse) in /home/runner/work/ExRam.Gremlinq/ExRam.Gremlinq/ExRam.Gremlinq.Core/Deserialization/GremlinQueryFragmentDeserializer.cs:line 33
   at lambda_method(Closure , JObject , Type , IGremlinQueryEnvironment , IGremlinQueryFragmentDeserializer )
   at ExRam.Gremlinq.Core.GremlinQueryExecutionResultDeserializer.<>c.<.cctor>b__11_13(JObject jObject, Type type, IGremlinQueryEnvironment env, Func`5 overridden, IGremlinQueryFragmentDeserializer recurse) in /home/runner/work/ExRam.Gremlinq/ExRam.Gremlinq/ExRam.Gremlinq.Core/Deserialization/GremlinQueryExecutionResultDeserializer.cs:line 273
   at ExRam.Gremlinq.Core.GremlinQueryFragmentDeserializer.GremlinQueryFragmentDeserializerImpl.<>c__DisplayClass4_0`1.<Override>b__0(TSerialized fragment, Type type, IGremlinQueryEnvironment env, Func`5 baseSerializer, IGremlinQueryFragmentDeserializer recurse) in /home/runner/work/ExRam.Gremlinq/ExRam.Gremlinq/ExRam.Gremlinq.Core/Deserialization/GremlinQueryFragmentDeserializer.cs:line 33
   at lambda_method(Closure , JObject , Type , IGremlinQueryEnvironment , IGremlinQueryFragmentDeserializer )
   at ExRam.Gremlinq.Core.GremlinQueryExecutionResultDeserializer.<>c.<.cctor>b__11_14(JObject jObject, Type type, IGremlinQueryEnvironment env, Func`5 overridden, IGremlinQueryFragmentDeserializer recurse) in /home/runner/work/ExRam.Gremlinq/ExRam.Gremlinq/ExRam.Gremlinq.Core/Deserialization/GremlinQueryExecutionResultDeserializer.cs:line 305
   at ExRam.Gremlinq.Core.GremlinQueryFragmentDeserializer.GremlinQueryFragmentDeserializerImpl.<>c__DisplayClass4_0`1.<Override>b__0(TSerialized fragment, Type type, IGremlinQueryEnvironment env, Func`5 baseSerializer, IGremlinQueryFragmentDeserializer recurse) in /home/runner/work/ExRam.Gremlinq/ExRam.Gremlinq/ExRam.Gremlinq.Core/Deserialization/GremlinQueryFragmentDeserializer.cs:line 33
   at lambda_method(Closure , JToken , Type , IGremlinQueryEnvironment , IGremlinQueryFragmentDeserializer )
   at ExRam.Gremlinq.Core.GremlinQueryFragmentDeserializer.GremlinQueryFragmentDeserializerImpl.TryDeserialize[TSerialized](TSerialized serializedData, Type fragmentType, IGremlinQueryEnvironment environment) in /home/runner/work/ExRam.Gremlinq/ExRam.Gremlinq/ExRam.Gremlinq.Core/Deserialization/GremlinQueryFragmentDeserializer.cs:line 22
   at ExRam.Gremlinq.Core.GremlinQueryExecutionResultDeserializer.<>c.<.cctor>b__11_17(JArray jArray, Type type, IGremlinQueryEnvironment env, Func`5 overridden, IGremlinQueryFragmentDeserializer recurse) in /home/runner/work/ExRam.Gremlinq/ExRam.Gremlinq/ExRam.Gremlinq.Core/Deserialization/GremlinQueryExecutionResultDeserializer.cs:line 349
   at ExRam.Gremlinq.Core.GremlinQueryFragmentDeserializer.GremlinQueryFragmentDeserializerImpl.<>c__DisplayClass4_0`1.<Override>b__0(TSerialized fragment, Type type, IGremlinQueryEnvironment env, Func`5 baseSerializer, IGremlinQueryFragmentDeserializer recurse) in /home/runner/work/ExRam.Gremlinq/ExRam.Gremlinq/ExRam.Gremlinq.Core/Deserialization/GremlinQueryFragmentDeserializer.cs:line 33
   at lambda_method(Closure , Object , Type , IGremlinQueryEnvironment , IGremlinQueryFragmentDeserializer )
   at ExRam.Gremlinq.Core.GremlinQueryFragmentDeserializer.GremlinQueryFragmentDeserializerImpl.TryDeserialize[TSerialized](TSerialized serializedData, Type fragmentType, IGremlinQueryEnvironment environment) in /home/runner/work/ExRam.Gremlinq/ExRam.Gremlinq/ExRam.Gremlinq.Core/Deserialization/GremlinQueryFragmentDeserializer.cs:line 22
   at ExRam.Gremlinq.Core.GremlinQueryExecutionResultDeserializer.GremlinQueryExecutionResultDeserializerImpl.Deserialize[TElement](Object executionResult, IGremlinQueryEnvironment environment) in /home/runner/work/ExRam.Gremlinq/ExRam.Gremlinq/ExRam.Gremlinq.Core/Deserialization/GremlinQueryExecutionResultDeserializer.cs:line 36
   at ExRam.Gremlinq.Core.GremlinQuery`6.<ExRam.Gremlinq.Core.IGremlinQueryBase<TElement>.ToAsyncEnumerable>b__208_0(Object executionResult) in /home/runner/work/ExRam.Gremlinq/ExRam.Gremlinq/ExRam.Gremlinq.Core/Queries/GremlinQuery.explicit.cs:line 232
   at System.Linq.AsyncEnumerable.SelectManyAsyncIterator`2.MoveNextCore() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/SelectMany.cs:line 463
   at System.Linq.AsyncIteratorBase`1.MoveNextAsync() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/AsyncIterator.cs:line 70
   at System.Linq.AsyncIteratorBase`1.MoveNextAsync() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/AsyncIterator.cs:line 75
   at System.Linq.AsyncEnumerable.<TryGetFirst>g__Core|291_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/FirstOrDefault.cs:line 119
   at System.Linq.AsyncEnumerable.<TryGetFirst>g__Core|291_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/FirstOrDefault.cs:line 121
   at System.Linq.AsyncEnumerable.<FirstOrDefaultAsync>g__Core|287_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/FirstOrDefault.cs:line 32
```
- a link to GitHub repository containing a minimal executable project
structure that exposes the unexpected behaviour. By 'minimal' we mean that you should omit any code
that is not directly necessary to show the unexpected behaviour. **Make sure you remove any sensible
data (e.g. passwords etc). Don't post tons of business POCOs or DTOs that
are not really relevant for exposing the unexpected behaviour.**

- a pull request to ExRam.Gremlinq that adds a failing unit test to the ExRam.Gremlinq tests asserting
the expected behaviour. Again, this should be minimal to reduce noise.

**In any case: The repro code must be able to checkout and run in the matter of minutes.**
If the issue contains neither of these things and/or just incomplete code snippets it may be labelled accordingly and become stale.
Please understand that I ask for this much effort from you in exchange for my work since
it is tedious and time-consuming to isolate the relevant bits from an issue each time just to setup
a new project that might not even fail then.

**Additional context**

**Comment by SaltyDH** [comment]
I'll do up a repro as requested. :)

**Comment by matt-psaltis** [comment]
I've been trying to build a repro test but I think I'm hitting a separate bug around the test framework for CosmosDB.

The test in the commit above represents the scenario I'm trying to get working. Instead of the exception thrown in the original description, I'm currently getting an exception. I'd love a quick nudge in the right direction if you wouldn't mind.

```
System.InvalidCastException
A result of type ExRam.Gremlinq.Core.GroovyGremlinQuery can't be interpreted as IAsyncEnumerable.
   at ExRam.Gremlinq.Core.GremlinQueryExecutionResultDeserializer.GremlinQueryExecutionResultDeserializerImpl.Deserialize[TElement](Object executionResult, IGremlinQueryEnvironment environment) in C:\git\sandbox\ExRam.Gremlinq\ExRam.Gremlinq.Core\Deserialization\GremlinQueryExecutionResultDeserializer.cs:line 46
   at ExRam.Gremlinq.Core.GremlinQuery`6.<ExRam.Gremlinq.Core.IGremlinQueryBase<TElement>.ToAsyncEnumerable>b__208_0(Object executionResult) in C:\git\sandbox\ExRam.Gremlinq\ExRam.Gremlinq.Core\Queries\GremlinQuery.explicit.cs:line 232
   at System.Linq.AsyncEnumerable.SelectManyAsyncIterator`2.ToListAsync(CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/SelectMany.cs:line 434
   at System.Linq.AsyncEnumerable.SelectManyAsyncIterator`2.ToListAsync(CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/SelectMany.cs:line 432
   at System.Linq.AsyncEnumerable.SelectManyAsyncIterator`2.ToArrayAsync(CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/SelectMany.cs:line 423
   at ExRam.Gremlinq.Core.GremlinQueryAwaiter`1.GetResult() in C:\git\sandbox\ExRam.Gremlinq\ExRam.Gremlinq.Core\Queries\GremlinQueryAwaiter.cs:line 17
   at ExRam.Gremlinq.Providers.CosmosDb.Tests.CosmosDbQuerySerializationTest.GuidDeserialization_Succeeds() in C:\git\sandbox\ExRam.Gremlinq\ExRam.Gremlinq.Providers.CosmosDb.Tests\CosmosDbQuerySerializationTest.cs:line 25
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 264
--- End of stack trace from previous location where exception was thrown ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 90
```

**Comment by danielcweber** [comment]
Don't await the query. Call Verify like in all the other tests (e.g. [here](https://github.com/ExRam/ExRam.Gremlinq/blob/b16380708b14d2fde3570debb93a4c3954f153fb/ExRam.Gremlinq.Core.Tests/QueryExecutionTest.cs#L75)).

**Comment by matt-psaltis** [comment]
Thanks @danielcweber I was working from the AddV_list_cardinality_id test originally as that was the only test that had an example of using FirstAsync. Which I believed was part of the underlying issue because its during deserialization of the returned value from the CosmosDB. Try as I might, I haven't been able to reproduce this using the existing test framework. I've built an integration test inside the existing test framework which fails for me connected to my local Cosmos DB emulator. I'm hoping that's sufficient to communicate this issue. The test is in this commit: https://github.com/matt-psaltis/ExRam.Gremlinq/commit/a61bd3ca7a69d1b2ff65742e7617d0b4b057e85b

Sorry I wasn't able to reduce this down to a unit test, happy to do so if there's any further suggestions.

**Comment by danielcweber** [comment]
As a quick workaround, configure Guid to be a native type:

**Comment by matt-psaltis** [comment]
@danielcweber Thank you very much for taking a look and for the feedback and workaround!

**Comment by YakanMS** [comment]
> As a quick workaround, configure Guid to be a native type:
> 
> ```
>             var g = GremlinQuerySource.g
>                 .ConfigureEnvironment(env => env
>                     .UseCosmosDb(builder => builder
>                         .At(new Uri("https://localhost:8081"), "Issue103", "Default")
>                         .AuthenticateBy(
>                             "authKey")
>                     .ConfigureModel(m => m.ConfigureNativeTypes(t => t.Add(typeof(Guid)))));
> ```
> 
> Note that for CosmosDB, Guid is not a native type. That's why the id property will always be deserialized to a string. Also, you need to add a PartitionKey property to the VertexWithGuid-class.

"As a quick walkaround" --> What do you suppose would be a complete, correct solution? having String properties instead of Guid ones? Is there a way to instruct Gremlinq to serialize Guid properties as strings and deserialize those string fields back to Guid properties?

**Comment by danielcweber** [comment]
Yes, the complete correct solution is to not have Guid-properties on vertices and edges. In any other case, the presented workaround is the most correct solution as well. By instructing Gremlinq to treat Guids as database native types, serialization and deserialization will do their best to map values, and it should just work.

But you should go for the string alternative.
