### ISSUE TITLE
Partition Key error on the example project

### ISSUE THREAD

**Issue by scphantm** [ExRam/ExRam.Gremlinq#463]
**Describe the bug**
The example project fails to load objects into database.  I cloned your examples, created a graph db in azure, and updated your program.cs to my credentials, uncommented the cosmosdb section.  When i run the program, i get this

```
Clearing the database...creating a new database...fail: Queries[0]
      Error executing Gremlin query with RequestId e934374e-a41a-433a-a343-6640b72dc60b: Gremlin.Net.Driver.Exceptions.ResponseException: ScriptEvaluationError: 
      
      ActivityId : ae9088f1-ddaf-4587-974b-6a2778ba6859
      ExceptionType : GraphRuntimeException
      ExceptionMessage : 
        Gremlin Query Execution Error: Cannot add a vertex where the partition key property has value 'null'.
        GremlinRequestId : e934374e-a41a-433a-a343-6640b72dc60b
        Context : graphcompute
        Scope : graphcomp-execquery
        GraphInterOpStatusCode : GraphRuntimeError
        HResult : 0x80131500
      
         at Gremlin.Net.Driver.Messages.ResponseStatusExtensions.ThrowIfStatusIndicatesError(ResponseStatus status)
         at Gremlin.Net.Driver.Connection.TryParseResponseMessage(ResponseMessage`1 receivedMsg)
         at Gremlin.Net.Driver.Connection.Parse(Byte[] received)
      --- End of stack trace from previous location where exception was thrown ---
         at Gremlin.Net.Driver.ProxyConnection.SubmitAsync[T](RequestMessage requestMessage)
         at Gremlin.Net.Driver.GremlinClient.SubmitAsync[T](RequestMessage requestMessage)
         at ExRam.Gremlinq.Core.GremlinClientExtensions.ObserveResultStatusAttributesGremlinClient.SubmitAsync[TResult](RequestMessage requestMessage) in /_/src/ExRam.Gremlinq.Providers.WebSocket/Extensions/GremlinClientExtensions.cs:line 46
         at ExRam.Gremlinq.Core.GremlinQueryEnvironmentExtensions.WebSocketGremlinQueryExecutor.<>c__DisplayClass6_0.<<Execute>g__Core|0>d.MoveNext() in /_/src/ExRam.Gremlinq.Providers.WebSocket/Extensions/GremlinQueryEnvironmentExtensions.cs:line 79
Unhandled exception. Gremlin.Net.Driver.Exceptions.ResponseException: ScriptEvaluationError: 

ActivityId : ae9088f1-ddaf-4587-974b-6a2778ba6859
ExceptionType : GraphRuntimeException
ExceptionMessage : 
        Gremlin Query Execution Error: Cannot add a vertex where the partition key property has value 'null'.
        GremlinRequestId : e934374e-a41a-433a-a343-6640b72dc60b
        Context : graphcompute
        Scope : graphcomp-execquery
        GraphInterOpStatusCode : GraphRuntimeError
        HResult : 0x80131500

   at Gremlin.Net.Driver.Messages.ResponseStatusExtensions.ThrowIfStatusIndicatesError(ResponseStatus status)
   at Gremlin.Net.Driver.Connection.TryParseResponseMessage(ResponseMessage`1 receivedMsg)
   at Gremlin.Net.Driver.Connection.Parse(Byte[] received)
--- End of stack trace from previous location where exception was thrown ---
   at Gremlin.Net.Driver.ProxyConnection.SubmitAsync[T](RequestMessage requestMessage)
   at Gremlin.Net.Driver.GremlinClient.SubmitAsync[T](RequestMessage requestMessage)
   at ExRam.Gremlinq.Core.GremlinClientExtensions.ObserveResultStatusAttributesGremlinClient.SubmitAsync[TResult](RequestMessage requestMessage) in /_/src/ExRam.Gremlinq.Providers.WebSocket/Extensions/GremlinClientExtensions.cs:line 46
   at ExRam.Gremlinq.Core.GremlinQueryEnvironmentExtensions.WebSocketGremlinQueryExecutor.<>c__DisplayClass6_0.<<Execute>g__Core|0>d.MoveNext() in /_/src/ExRam.Gremlinq.Providers.WebSocket/Extensions/GremlinQueryEnvironmentExtensions.cs:line 79
--- End of stack trace from previous location where exception was thrown ---
   at ExRam.Gremlinq.Core.GremlinQueryEnvironmentExtensions.WebSocketGremlinQueryExecutor.<>c__DisplayClass6_0.<<Execute>g__Core|0>d.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
   at System.Linq.AsyncEnumerable.SelectManyAsyncIterator`2.MoveNextCore() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/SelectMany.cs:line 456
   at System.Linq.AsyncIteratorBase`1.MoveNextAsync() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/AsyncIterator.cs:line 70
   at System.Linq.AsyncIteratorBase`1.MoveNextAsync() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/AsyncIterator.cs:line 75
   at System.Linq.AsyncEnumerable.<TryGetFirst>g__Core|291_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/FirstOrDefault.cs:line 119
   at System.Linq.AsyncEnumerable.<TryGetFirst>g__Core|291_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/FirstOrDefault.cs:line 121
   at System.Linq.AsyncEnumerable.<FirstAsync>g__Core|283_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/First.cs:line 31
   at ExRam.Gremlinq.Samples.Shared.Logic.Create_the_graph() in /Users/william.slepecki/Downloads/ExRam.Gremlinq.Samples-main/ExRam.Gremlinq.Samples.Shared/Logic.cs:line 61
   at ExRam.Gremlinq.Samples.Shared.Logic.Run() in /Users/william.slepecki/Downloads/ExRam.Gremlinq.Samples-main/ExRam.Gremlinq.Samples.Shared/Logic.cs:line 28
   at ExRam.Gremlinq.Samples.Program.Main() in /Users/william.slepecki/Downloads/ExRam.Gremlinq.Samples-main/ExRam.Gremlinq.Samples.Console/Program.cs:line 65
   at ExRam.Gremlinq.Samples.Program.<Main>()

Process finished with exit code 134.
```
I read about PartitionKey errors in other stuff here and modified the line on the `Vertex.cs` to this

`public CosmosDbKey PartitionKey { get; set; } = new CosmosDbKey("mykey", "id");`

and got past this error, but got this one.

```
/usr/local/share/dotnet/dotnet /Users/william.slepecki/Downloads/ExRam.Gremlinq.Samples-main/ExRam.Gremlinq.Samples.Console/bin/Debug/netcoreapp3.1/ExRam.Gremlinq.Samples.Console.dll
Clearing the database...creating a new database...fail: Queries[0]
      Error executing Gremlin query with RequestId 433b7db1-4e92-48cc-897e-38c128a072bb: Gremlin.Net.Driver.Exceptions.ResponseException: ScriptEvaluationError: 
      
      ActivityId : 7fb12578-bffc-44b5-a811-32b3078e0a23
      ExceptionType : GraphRuntimeException
      ExceptionMessage : 
        Gremlin Query Execution Error: Cannot create ValueField on non-primitive type List`1.
        GremlinRequestId : 433b7db1-4e92-48cc-897e-38c128a072bb
        Context : graphcompute
        Scope : graphstg-logplan
        GraphInterOpStatusCode : GraphRuntimeError
        HResult : 0x80131500
      
         at Gremlin.Net.Driver.Messages.ResponseStatusExtensions.ThrowIfStatusIndicatesError(ResponseStatus status)
         at Gremlin.Net.Driver.Connection.TryParseResponseMessage(ResponseMessage`1 receivedMsg)
         at Gremlin.Net.Driver.Connection.Parse(Byte[] received)
      --- End of stack trace from previous location where exception was thrown ---
         at Gremlin.Net.Driver.ProxyConnection.SubmitAsync[T](RequestMessage requestMessage)
         at Gremlin.Net.Driver.GremlinClient.SubmitAsync[T](RequestMessage requestMessage)
         at ExRam.Gremlinq.Core.GremlinClientExtensions.ObserveResultStatusAttributesGremlinClient.SubmitAsync[TResult](RequestMessage requestMessage) in /_/src/ExRam.Gremlinq.Providers.WebSocket/Extensions/GremlinClientExtensions.cs:line 46
         at ExRam.Gremlinq.Core.GremlinQueryEnvironmentExtensions.WebSocketGremlinQueryExecutor.<>c__DisplayClass6_0.<<Execute>g__Core|0>d.MoveNext() in /_/src/ExRam.Gremlinq.Providers.WebSocket/Extensions/GremlinQueryEnvironmentExtensions.cs:line 79
Unhandled exception. Gremlin.Net.Driver.Exceptions.ResponseException: ScriptEvaluationError: 

ActivityId : 7fb12578-bffc-44b5-a811-32b3078e0a23
ExceptionType : GraphRuntimeException
ExceptionMessage : 
        Gremlin Query Execution Error: Cannot create ValueField on non-primitive type List`1.
        GremlinRequestId : 433b7db1-4e92-48cc-897e-38c128a072bb
        Context : graphcompute
        Scope : graphstg-logplan
        GraphInterOpStatusCode : GraphRuntimeError
        HResult : 0x80131500

   at Gremlin.Net.Driver.Messages.ResponseStatusExtensions.ThrowIfStatusIndicatesError(ResponseStatus status)
   at Gremlin.Net.Driver.Connection.TryParseResponseMessage(ResponseMessage`1 receivedMsg)
   at Gremlin.Net.Driver.Connection.Parse(Byte[] received)
--- End of stack trace from previous location where exception was thrown ---
   at Gremlin.Net.Driver.ProxyConnection.SubmitAsync[T](RequestMessage requestMessage)
   at Gremlin.Net.Driver.GremlinClient.SubmitAsync[T](RequestMessage requestMessage)
   at ExRam.Gremlinq.Core.GremlinClientExtensions.ObserveResultStatusAttributesGremlinClient.SubmitAsync[TResult](RequestMessage requestMessage) in /_/src/ExRam.Gremlinq.Providers.WebSocket/Extensions/GremlinClientExtensions.cs:line 46
   at ExRam.Gremlinq.Core.GremlinQueryEnvironmentExtensions.WebSocketGremlinQueryExecutor.<>c__DisplayClass6_0.<<Execute>g__Core|0>d.MoveNext() in /_/src/ExRam.Gremlinq.Providers.WebSocket/Extensions/GremlinQueryEnvironmentExtensions.cs:line 79
--- End of stack trace from previous location where exception was thrown ---
   at ExRam.Gremlinq.Core.GremlinQueryEnvironmentExtensions.WebSocketGremlinQueryExecutor.<>c__DisplayClass6_0.<<Execute>g__Core|0>d.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
   at System.Linq.AsyncEnumerable.SelectManyAsyncIterator`2.MoveNextCore() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/SelectMany.cs:line 456
   at System.Linq.AsyncIteratorBase`1.MoveNextAsync() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/AsyncIterator.cs:line 70
   at System.Linq.AsyncIteratorBase`1.MoveNextAsync() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/AsyncIterator.cs:line 75
   at System.Linq.AsyncEnumerable.<TryGetFirst>g__Core|291_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/FirstOrDefault.cs:line 119
   at System.Linq.AsyncEnumerable.<TryGetFirst>g__Core|291_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/FirstOrDefault.cs:line 121
   at System.Linq.AsyncEnumerable.<FirstAsync>g__Core|283_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/First.cs:line 31
   at ExRam.Gremlinq.Samples.Shared.Logic.Create_the_graph() in /Users/william.slepecki/Downloads/ExRam.Gremlinq.Samples-main/ExRam.Gremlinq.Samples.Shared/Logic.cs:line 61
   at ExRam.Gremlinq.Samples.Shared.Logic.Run() in /Users/william.slepecki/Downloads/ExRam.Gremlinq.Samples-main/ExRam.Gremlinq.Samples.Shared/Logic.cs:line 28
   at ExRam.Gremlinq.Samples.Program.Main() in /Users/william.slepecki/Downloads/ExRam.Gremlinq.Samples-main/ExRam.Gremlinq.Samples.Console/Program.cs:line 65
   at ExRam.Gremlinq.Samples.Program.<Main>()

Process finished with exit code 134.
```

**Expected behavior**
I expected it to add the data to the graph.

**Version information**
8.6.0

**Minimal working example**
I am using your example project.

**Comment by danielcweber** [comment]
The Vertex base class in the samples project contains a property "PartitionKey" with a default value. So my guess is that you're either not using the base class or got the value overwritten/deleted somehow. For any further insight, I'd need something to run.

**Comment by scphantm** [comment]
im running your sample project.  all i changed in that project was the connection information for my db.  i changed nothing else.

**Comment by scphantm** [comment]
https://github.com/ExRam/ExRam.Gremlinq.Samples

is the project im trying to run

**Comment by danielcweber** [comment]
Try changing the property name "PartitionKey" to match the name of the partition key you set up in CosmosDB. Also mind casing!

**Comment by scphantm** [comment]
Ah, that fixed it.  Didn't realize that field name had to match up.
