### ISSUE TITLE
Lookup vertex by tuple

### ISSUE THREAD

**Issue by smokedlinq** [ExRam/ExRam.Gremlinq#525]
**Is your feature request related to a problem? Please describe.**
For CosmosDb graph support, they recommend using tuples to find a vertex by partition key and id, e.g. `V(["partitionKey", "id"])`. To do this today: `V<Vertex>(new object[] { new string[] { "partitionKey", "id" } })`.

**Describe the solution you'd like**
It would be ideal to be able to do: `V<Vertex>(("partitionKey", "id"))`; or getting multiple: `V<Vertex>(("partitionKey1", "id1"), ("partitionKey2", "id2"))`

**Describe alternatives you've considered**
Tried an extension method that does the transform but since `V<T>(ids)` takes a params, it seems the compiler always wants to use that vs the extension method unless you explicitly state the parameter name, e.g. `V<Vertex>(tuples: ("partitionKey1", "id1"), ("partitionKey2", "id2"))`

**Additional context**
If you try to pass a tuple `V<Vertex>(("partitionKey", "id"))`, you see the query looks right but the binding does not ...

```
Executing Gremlin query {"RequestId":"a1c5603d-2251-40d3-a08c-f51a7580e827","Script":"V(_a).hasLabel(_b)","Bindings":{"_a":{"Item1":"partitionKey","Item2":"id"},"_b":"vertex"}}

Error executing Gremlin query with RequestId a1c5603d-2251-40d3-a08c-f51a7580e827: System.InvalidOperationException: [NullGuard] Return value of method 'System.Threading.Tasks.Task`1<Gremlin.Net.Driver.Messages.ResponseMessage`1<System.Collections.Generic.List`1<System.Object>>> ExRam.Gremlinq.Core.JsonNetMessageSerializer::DeserializeMessageAsync(System.Byte[])' is null.
         at Gremlin.Net.Driver.Connection.HandleReceivedAsync(Byte[] received)
         at Gremlin.Net.Driver.Connection.ReceiveMessagesAsync()
         at Gremlin.Net.Driver.ProxyConnection.SubmitAsync[T](RequestMessage requestMessage)
         at Gremlin.Net.Driver.GremlinClient.SubmitAsync[T](RequestMessage requestMessage)
         at ExRam.Gremlinq.Core.GremlinClientExtensions.ObserveResultStatusAttributesGremlinClient.SubmitAsync[TResult](RequestMessage requestMessage) in /_/src/ExRam.Gremlinq.Providers.WebSocket/Extensions/GremlinClientExtensions.cs:line 46
         at ExRam.Gremlinq.Core.ConfigurableGremlinQuerySourceExtensions.WebSocketGremlinQueryExecutor.<>c__DisplayClass6_0.<<Execute>g__Core|0>d.MoveNext() in /_/src/ExRam.Gremlinq.Providers.WebSocket/Extensions/ConfigurableGremlinQuerySourceExtensions.cs:line 93
```

**Comment by danielcweber** [comment]
Use a [CosmosDbKey](https://github.com/ExRam/ExRam.Gremlinq/blob/main/src/ExRam.Gremlinq.Providers.CosmosDb/CosmosDbKey.cs).

**Comment by smokedlinq** [comment]
Ah, got it. Thanks
