### ISSUE TITLE
COSMOS: Update vertex errors with the partition property cannot be removed

### ISSUE THREAD

**Issue by smokedlinq** [ExRam/ExRam.Gremlinq#568]
**Describe the bug**
Doing a simple update of a simple vertex that has no properties (it's a generic method) other than Id/PartitionKey. It appears it's generating a query to drop all properties.

```csharp
private async Task UpdateVertexAsync<T>(T vertex, CosmosDbKey key) where T : Vertex
{
    await _graph.V<VertexName>(key).Update(vertex);
}
```

Log output:
```
[2022-03-09T14:08:53.280Z] Executing Gremlin query {"RequestId":"5f971b7b-dfdf-45a0-a791-54d814ededcc","Script":"V(_a).hasLabel(_b).sideEffect(__.properties().drop())","Bindings":null}.
fail: Graph.Cosmos.CosmosGraphSource[0]
      Error executing Gremlin query with RequestId 5f971b7b-dfdf-45a0-a791-54d814ededcc: Gremlin.Net.Driver.Exceptions.ResponseException: ServerEvaluationError:

ActivityId : 63bc7d00-ea21-454f-9f69-49c7cbd5617e
ExceptionType : GraphRuntimeException
ExceptionMessage :
        Gremlin Query Execution Error: The partition property cannot be removed.
        GremlinRequestId : 5f971b7b-dfdf-45a0-a791-54d814ededcc
        Context : graphcompute
        Scope : graphcomp-execquery
        GraphInterOpStatusCode : GraphRuntimeError
        HResult : 0x80131500

         at Gremlin.Net.Driver.Messages.ResponseStatusExtensions.ThrowIfStatusIndicatesError(ResponseStatus status)
         at Gremlin.Net.Driver.Connection.HandleReceivedMessage(ResponseMessage`1 receivedMsg)
         at Gremlin.Net.Driver.Connection.HandleReceivedAsync(Byte[] received)
         at Gremlin.Net.Driver.ProxyConnection.SubmitAsync[T](RequestMessage requestMessage)
         at Gremlin.Net.Driver.GremlinClient.SubmitAsync[T](RequestMessage requestMessage)
         at ExRam.Gremlinq.Core.GremlinClientExtensions.ObserveResultStatusAttributesGremlinClient.SubmitAsync[TResult](RequestMessage requestMessage) in /_/src/ExRam.Gremlinq.Providers.WebSocket/Extensions/GremlinClientExtensions.cs:line 46
         at ExRam.Gremlinq.Core.ConfigurableGremlinQuerySourceExtensions.WebSocketGremlinQueryExecutor.<>c__DisplayClass6_0.<<Execute>g__Core|0>d.MoveNext() in /_/src/ExRam.Gremlinq.Providers.WebSocket/Extensions/ConfigurableGremlinQuerySourceExtensions.cs:line 93
```

**Expected behavior**
If there are no properties that can be updated no query against graph should be made.

**Version information**
```xml
<PackageReference Include="ExRam.Gremlinq.Providers.CosmosDb" Version="9.2.0" />
```

**Minimal working example**
Not sure this code will compile but it's providing the general idea:

```csharp
public class Vertex
{
    public string Id {get; set;}
    public string PartitionKey {get;set;}
}
public class Thing : Vertex
{
}

var thing = new Thing()
{
  Id = "id",
  PartitionKey = "partition-key"
};
await _g.AddV(thing);
await _g.V<Thing>(new CosmosDb(thing.PartitionKey, thing.Id)).Update(thing);
```

**Comment by smokedlinq** [comment]
I get that this is probably because it didn't detect any changes and I'll code around it for the time being but would be nice not to have to be concerned with if a vertex has properties or not.
