### ISSUE TITLE
Unable to generate idempotent Gremlin query using Coalesce

### ISSUE THREAD

**Issue by GarethJames** [ExRam/ExRam.Gremlinq#62]
Hi,

I'm using Gremlinq to connect to a Cosmos Graph DB. I'm trying to create a Gremlinq expression that adds vertices and edges if they don't already exist. This is so that the query is idempotent and can be retried. The Gremlin query I'm trying to produce looks something like this (borrowed from [https://medium.com/@jayanta.mondal/cosmos-db-graph-gremlin-api-how-to-executing-multiple-writes-as-a-unit-via-a-single-gremlin-2ce82d8bf365](https://medium.com/@jayanta.mondal/cosmos-db-graph-gremlin-api-how-to-executing-multiple-writes-as-a-unit-via-a-single-gremlin-2ce82d8bf365))
```
g.V("userId").has("pk", "pkValue1").as("creator")
    .coalesce(
        g.V("tweetId").has("pk", "pkValue2"),
        addV("tweet")
            .property("id", "tweetId")
            .property("pk", "pkValue2")
            .property("content", "blah")
        ).as ("tweet")
    .coalesce(
        g.E().has("id", "edgeId").has("pk", "pkValue2"),
        addE("created by")
            .property("id", "edgeId")
            .to("creator")
        );
```
The closest I've managed to get is as follows:
```csharp
IVertex tweetVertex = default!;
IVertex tweetEdge = default!;

await _g
    .V<IVertex>("userId")
        .Where(x => x.pk == "pkValue1")
        .As((__, creator) => __
            .Coalesce(
                (q) => _g.V<IVertex>("tweetId").Where(x => x.pk == "pkValue2"),
                (q) => _g.AddV(tweetVertex)
                                .Property("id", "tweetId")
                                .Property("pk", "pkValue2")
                                .Property("content", "blah")
            )
            .As((___, tweet) => ___
                .Coalesce(
                    (q) => _g.E<IEdge>("edgeId").Where(x => x.pk == "pkValue2"),
                    (q) => (IEdgeGremlinQuery<IEdge>)_g.AddE(tweetEdge)
                                                            .Property("id", "edgeId")
                                                            .To(creator)
                )
            )
        );
```
_NB: I've used IVertex and IEdge in place of real C# objects for convenience here._

The query that is generated is a _lot_ more verbose, but the main issue I have is that the traversals in the Coalesce steps always seem to produce these **underscores** in the Coalesce traversals:
```
g.V("userId").has("pk", "pkValue1").as("creator")
    .coalesce(
        __.V("tweetId").has("pk", "pkValue2"),
        __.addV("tweet")
            .property("id", "tweetId")
            .property("pk", "pkValue2")
            .property("content", "blah")
        ).as ("tweet")
    .coalesce(
        __.E().has("id", "edgeId").has("pk", "pkValue2"),
        __.addE("created by")
            .property("id", "edgeId")
            .to("creator")
        );
```
I can't seem to find a way of having **g** or nothing at all rather than **__** in the traversals of the Coalesce step. Is this possible with Gremlinq?

Many thanks,
Gareth

**Comment by danielcweber** [comment]
>(q) => _g.V<IVertex>("tweetId").Where(x => x.pk == "pkValue2"),

always! use the provided continuation query that's passed in. Never reuse _g mid-query.

Aside from that, I'm not really sure what you're asking for. You don't want to have "__" appear in the generated gremlin ?

**Comment by GarethJames** [comment]
I have tried using `(q) => q.V("tweetId").Where(x => x.pk == "pkValue2")` and `(q) => __.V("tweetId").Where(x => x.pk == "pkValue2")` but to no avail. The issue is the where the following is generated:
```
        __.V("tweetId").has("pk", "pkValue2"),
        __.addV("tweet")
            .property("id", "tweetId")
            .property("pk", "pkValue2")
            .property("content", "blah")
        ).as ("tweet")
```
I need it to be:
```
        g.V("tweetId").has("pk", "pkValue2"),
        addV("tweet")
            .property("id", "tweetId")
            .property("pk", "pkValue2")
            .property("content", "blah")
        ).as ("tweet")
```
As per the example from the article I linked to.

**Comment by danielcweber** [comment]
It's equivalent. What's your issue with "__"? __ is implicit in Gremlin if you omit it.

**Comment by GarethJames** [comment]
Cosmos DB returns an exception trying to compile the query, whereas if I remove the underscores the query succeeds. The actual code I'm running looks like this:
```csharp
await _g
    .V<OrganisationVertex>(pendingCustomerEdge.SourceVertexId)
        .Where(x => x.pk == pendingCustomerEdge.SourceVertexId)
        .As((__, org) => __
            .Coalesce(
                (q) => q.V<CustomerVertex>(customerId).Where(x => x.pk == customerId),
                (q) => q.AddV(customerVertex)
            )
            .As((___, cus) => ___
                .Coalesce(
                    (q) => q.E<CustomerOrganisationEdge>(customerToOrganisationId).Where(x => x.pk == customerId),
                    (q) => (IEdgeGremlinQuery<CustomerOrganisationEdge>)q.AddE(customerOrganisationEdge).To(org)
                )
            )
        );
```
and the Gremlin query produced like this:
```
g.V("1abf87e7-2047-42bd-89e1-bc19b5b42e80").hasLabel("OrganisationVertex").has("pk", "1abf87e7-2047-42bd-89e1-bc19b5b42e80")
    .as("l1")
    .coalesce(
        __.V("467820c3-384f-400d-9935-d9f67d99086d").hasLabel("CustomerVertex").has("pk", "467820c3-384f-400d-9935-d9f67d99086d"),
        __.addV("CustomerVertex")
            .property(single, "EmailAddress", "***********")
            .property(single, "FirstName", "Firstname")
            .property(id, "467820c3-384f-400d-9935-d9f67d99086d")
            .property(single, "LastName", "Lastname")
            .property(single, "OrganisationId", "1abf87e7-2047-42bd-89e1-bc19b5b42e80")
            .property(single, "OrganisationName", "OrgName")
            .property(single, "pk", "467820c3-384f-400d-9935-d9f67d99086d")
    )
    .as("l2")
    .coalesce(
        __.E("e2c6aee7-6f52-41a8-b2de-0228726c44d5").hasLabel("CustomerOrganisationEdge").has("pk", "467820c3-384f-400d-9935-d9f67d99086d"),
        __.addE("CustomerOrganisationEdge")
            .property(id, "e2c6aee7-6f52-41a8-b2de-0228726c44d5")
            .property("OrganisationId", "1abf87e7-2047-42bd-89e1-bc19b5b42e80")
            .property("OrganisationName", "OrgName")
            .property("pk", "467820c3-384f-400d-9935-d9f67d99086d")
            .property("SourceVertexId", "467820c3-384f-400d-9935-d9f67d99086d")
            .to("l1")
    )
    .project("id", "label", "type", "properties").by(id).by(label).by(__.constant("edge")).by(__.valueMap())
```
The exception is as follows:
```
Gremlin.Net.Driver.Exceptions.ResponseException: ScriptEvaluationError: 

ActivityId : c330a33f-210a-4781-b7b7-ef33f05d292e
ExceptionType : GraphCompileException
ExceptionMessage :
	Gremlin Query Compilation Error: This step only can be a start step.
Source : Microsoft.Azure.Cosmos.Gremlin.Core
	GremlinRequestId : c330a33f-210a-4781-b7b7-ef33f05d292e
	Context : graphcompute
	Scope : graphstg-logplan
	GraphInterOpStatusCode : QuerySyntaxError
	HResult : 0x80131500

   at Gremlin.Net.Driver.Messages.ResponseStatusExtensions.ThrowIfStatusIndicatesError(ResponseStatus status)
   at Gremlin.Net.Driver.Connection.TryParseResponseMessage(ResponseMessage`1 receivedMsg)
   at Gremlin.Net.Driver.Connection.Parse(Byte[] received)
--- End of stack trace from previous location where exception was thrown ---
   at Gremlin.Net.Driver.ProxyConnection.SubmitAsync[T](RequestMessage requestMessage)
   at Gremlin.Net.Driver.GremlinClient.SubmitAsync[T](RequestMessage requestMessage)
   at Gremlin.Net.Driver.GremlinClientExtensions.SubmitAsync[T](IGremlinClient gremlinClient, String requestScript, Dictionary`2 bindings)
   at ExRam.Gremlinq.Core.GremlinQueryEnvironmentExtensions.WebSocketGremlinQueryExecutor.<>c__DisplayClass7_0.<<Execute>g__Core|0>d.MoveNext() in /home/vsts/work/1/s/ExRam.Gremlinq.Providers.WebSocket/GremlinQueryEnvironmentExtensions.cs:line 59
```

**Comment by danielcweber** [comment]
Query looks right to me. Can you make it minimal such that the query with "__" would not work when the query without would ?

**Comment by GarethJames** [comment]
I'm not sure what you mean. Do you mean what's the minimal change I have to make to the query to get it to work? If I run the above query in the Azure Portal it fails with the same exception. If I alter it manually as follows:
```
g.V("1abf87e7-2047-42bd-89e1-bc19b5b42e80").hasLabel("OrganisationVertex").has("pk", "1abf87e7-2047-42bd-89e1-bc19b5b42e80")
    .as("l1")
    .coalesce(
        g.V("467820c3-384f-400d-9935-d9f67d99086d").hasLabel("CustomerVertex").has("pk", "467820c3-384f-400d-9935-d9f67d99086d"),
        addV("CustomerVertex")
            .property(single, "EmailAddress", "***********")
            .property(single, "FirstName", "Firstname")
            .property(id, "467820c3-384f-400d-9935-d9f67d99086d")
            .property(single, "LastName", "Lastname")
            .property(single, "OrganisationId", "1abf87e7-2047-42bd-89e1-bc19b5b42e80")
            .property(single, "OrganisationName", "OrgName")
            .property(single, "pk", "467820c3-384f-400d-9935-d9f67d99086d")
    )
    .as("l2")
    .coalesce(
        g.E("e2c6aee7-6f52-41a8-b2de-0228726c44d5").hasLabel("CustomerOrganisationEdge").has("pk", "467820c3-384f-400d-9935-d9f67d99086d"),
        addE("CustomerOrganisationEdge")
            .property(id, "e2c6aee7-6f52-41a8-b2de-0228726c44d5")
            .property("OrganisationId", "1abf87e7-2047-42bd-89e1-bc19b5b42e80")
            .property("OrganisationName", "OrgName")
            .property("pk", "467820c3-384f-400d-9935-d9f67d99086d")
            .property("SourceVertexId", "467820c3-384f-400d-9935-d9f67d99086d")
            .to("l1")
    )
    .project("id", "label", "type", "properties").by(id).by(label).by(__.constant("edge")).by(__.valueMap())
```
It succeeds.

**Comment by danielcweber** [comment]
The below query can't be right. You just don't use "g" mid-query. It may succeed, CosmosDB might look over that, it might have a bug or not, but this is not valid gremlin.

What I meant was: Please minimize the example to where it still shows the bug, but can't be minimized further.

**Comment by danielcweber** [comment]
It came to me as a surpirse as well: You can't have `E(...)` mid-query either, though Gremlinq interfaces allow for that. Try `g.V().E()` on the CosmosDB console, it'll reproduce your above error. Got nothing to do with underscores. In fact, CosmosDB's implementation adheres to the [Tinkerpop Api for traversals](http://tinkerpop.apache.org/javadocs/current/core/org/apache/tinkerpop/gremlin/process/traversal/dsl/graph/GraphTraversal.html) which has a V step but not an E step.

**Comment by danielcweber** [comment]
About using 'g' mid-query: It is actually valid after all, though it doesn't occur a lot in what can be found around the web. There doesn't seem to be much use for it except for the case you mentioned above, where you would have an E() query in the middle of the query. I'm afraid Gremlinq, as it is currently, doesn't support starting fresh from 'g' in the middle of a query.

**Comment by GarethJames** [comment]
Ah, okay; that makes sense. I really appreciate you taking the time to investigate the issue anyway.
Many thanks,
Gareth

**Comment by danielcweber** [comment]
BTW, you can simulate "__.E(...)" by "__.V().OutE().Where(....)". The performance of that query might be low though, and take a lot of RUs with CosmosDB. It's definitely worth a try.
