### ISSUE TITLE
Source sequence doesn't contain any elements.

### ISSUE THREAD

**Issue by haseebahmed7** [ExRam/ExRam.Gremlinq#80]
**Describe the bug**
When I try to add vertices to Cosmos DB, I get the following message & stack trace.

Error Message: Source sequence doesn't contain any elements.
Stack Trace:
```
   at System.Linq.AsyncEnumerable.<<FirstAsync>g__Core|283_0>d`1.MoveNext() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/First.cs:line 33
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at RoadHuntin.Library.Core.Create.Handler`2.<Handle>d__3.MoveNext() in E:\Code\RoadHuntinClient\backend\src\RoadHuntin.Library\Core\Create.cs:line 37
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.<Handle>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.<Handle>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.<Handle>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.<Handle>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.<Handle>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.<Handle>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at RoadHuntin.WebAPI.Controllers.RoutesController.<Post>d__4.MoveNext() in E:\Code\RoadHuntinClient\backend\src\RoadHuntin.WebAPI\Controllers\RoutesController.cs:line 46
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.<Execute>d__0.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<<InvokeActionMethodAsync>g__Logged|12_1>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<<InvokeNextActionFilterAsync>g__Awaited|10_0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<<InvokeInnerFilterAsync>g__Awaited|13_0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<<InvokeNextExceptionFilterAsync>g__Awaited|25_0>d.MoveNext()
```

**Expected behavior**
Vertex should be created and returned.

**Version information**
- ExRam.Gremlinq.Providers.CosmosDb 8.0.0-preview-0707
- ExRam.Gremlinq.Core 8.0.0-preview-0707

**Minimal working example**
This is the code from where the error is being generated:

DI registration::
```
services.AddScoped<IGremlinQuerySource>(provider => {
                var logger = provider.GetService<ILogger<IGremlinQuerySource>>();
                var options = (provider.GetService<IOptions<GremlinOptions>>()).Value;

                return g
                    .ConfigureEnvironment(env => env
                        .UseLogger(logger)
                        .UseModel(GraphModel
                            .FromBaseTypes<Vertex, Edge>(lookup => lookup.IncludeAssembliesOfBaseTypes())
                            .ConfigureProperties(model => model
                                .ConfigureElement<Vertex>(conf => conf.IgnoreOnUpdate(x => x.PartitionKey))
                                )
                            )
                        .UseCosmosDb(builder => builder
                            .At(new Uri(options.EndpointUri), options.Database, options.Container)
                            .AuthenticateBy(options.PrimaryKey)
                            .ConfigureWebSocket(builder => builder
                                .ConfigureQueryLoggingOptions(o => o
                                    .SetQueryLoggingVerbosity(QueryLoggingVerbosity.QueryAndParameters))
                                )
                            )
                        );
            });
```

Code Usage:
```
var model = _mapper.Map<TEntity>(request);
model = await _g.V<TEntity>().AddV(model).FirstAsync();
````

**Additional context**
- This was working before and has suddenly stopped working and I can't see any error or exceptions.
- I tried reverting my code to the old stage and still the same error.
- What I was doing was, I was storing non GraphSON documents on the CosmosDB alongside the usual GraphSON therefore I am using GremlinQ and ComsosDB SQL.NET API side-by-side. I was able to get it working last night but since today morning I've been seeing this error now with no idea how-to debug it. I thought I might've messed something in the CosmosDB so I've tried:
    - Different containers (this doesn't work), I get the same error.
    - I tried creating a new vertices from gremlin via Web Portal, this works as expected.

I think my main issue is how-to debug this since I'm getting no error which I'd assume means that everything went alright so FirstAsync() should work.

**Comment by haseebahmed7** [comment]
I have a theory,  so my folder structure is something like:

- ConsoleApp (with Startup where `IGremlinQuerySource` is registered with DI)
- Library (where `_g.AddV()` is being done)

When I move the `_g.AddV()` command to my ConsoleApp, it works but in the same code, when it is called from Library code it does not work! Could this have something to do with `ExRam.Gremlinq.Core.GremlinQuerySource` being static?

**Comment by haseebahmed7** [comment]
@danielcweber So I've identifier the behavior but I'll need your help for the solution :-)

**The flow?**
-> ConsoleApp.Run() (MyProject) -> Create.Handler() (MyProject.Library) -> _g.AddV()

**How it does not work?**
I don't see the data being entered into Cosmod DB if I register the Create.Handler in a static extenstion via MyProject.Library.

Code in Startup.cs (MyProject)
```
private static void ConfigureServices(IServiceCollection services)
{
    services.AddMyHandlers();
}
```

Code in (MyProject.Library)
```
public static IServiceCollection AddMyHandlers(this IServiceCollection services)
{
      services.AddScoped(
          typeof(IRequestHandler<Command, CommandResultViewModel>),
          typeof(Library.Core.Create.Handler<Create.Command, Models.Vertices.MyVertice>)
      );

      return services;
}
```

**How it does work?**

Code in Startup.cs (MyProject)
```
private static void ConfigureServices(IServiceCollection services)
{
    services.AddScoped(
          typeof(IRequestHandler<Command, CommandResultViewModel>),
          typeof(Library.Core.Create.Handler<Create.Command, Models.Vertices.MyVertice>)
      );
}
```

My Gremlin DI registration and calling remains the same as in the original issue. For more context, I've tried registering gremlin in two ways: 1) as an extension method in MyProject.Library 2) directly in MyProject's Startup. Either way, as long as the Handlers are registered via Extension method in MyProject.Library, `_g.AddV()` does not add anything and does not throw any errors either.

**Comment by danielcweber** [comment]
On first sight, you definitely want to register everything Gremlin as Singleton to avoid recreation on every query.

**Comment by haseebahmed7** [comment]
@danielcweber Let me see if that helps. Out of curiosity, how is recreation on every query a problem? In my case, I'm using a Scoped lifetime, which is what I would do with EF DbContext as well therefore it should be created once per each request.

Apologies if these questions sound novice but due to the lack of documentation around how-to setup I tried to follow the sample (which for is only for console apps) so I tried the best I could based on my previous experience with object mappers :-)

**Comment by danielcweber** [comment]
>how is recreation on every query a problem

You simply don't want to do the whole setup again and again, just for performance reasons.

**Comment by haseebahmed7** [comment]
> > how is recreation on every query a problem
> 
> You simply don't want to do the whole setup again and again, just for performance reasons.

Got it! I thought there might be some other reason as well. Maybe its just how Gremlinq is designed in comparison to EF that recreating a DbContext on every request is a common practice. Hopefully once I'm done with my current milestone, I'll spend some time getting into the Gremlinq code and understanding it better.

For now, changing it to singleton solves my problem and the code is working as expected. I'm going to run some more tests later. Once again, thank you for your effort! I'll try and add some documentation around setting up Gremlinq with DI. Do you think this project would be a good place for that or the sample project?

**Comment by danielcweber** [comment]
Note that there's Gremlinq.*.AspNet packages that handle DI just fine. Even less documentation there though, but it's all in the code and in the tests.

If you want to contribute, the Samples-Project could very well benefit from a second project that does the same but by utilizing the *.AspNet packages if you manage to figure things out from the code.

**Comment by haseebahmed7** [comment]
Changing it to Singleton worked! Thank you for your help. Closing this issue.

**Comment by jonathaneckman** [comment]
@danielcweber I am seeing this same error on some queries but not others

Works fine:
- inserts
- queries that return no results

Fails with this error:
- queries that return results
- updates (the update is working so I believe it is failing at returning the updated item)

This is how I've wired up the service in a dotnet core project. Any tips on what I may have missed?

```
services.AddGremlinq(a => new GremlinqSetup(services)
                .ConfigureEnvironment(env => env //We call ConfigureEnvironment twice so that the logger is set on the environment from now on.
                    .UseLogger(LoggerFactory
                        .Create(builder => builder
                            .AddFilter(__ => true)
                            .AddConsole())
                        .CreateLogger("Queries")))
                .ConfigureEnvironment(env => env
                    //Since the Vertex and Edge classes contained in this sample implement IVertex resp. IEdge,
                    //setting a model is actually not required as long as these classes are discoverable (i.e. they reside
                    //in a currently loaded assembly). We explicitly set a model here anyway.
                    .UseModel(GraphModel
                        .FromBaseTypes<Vertex, Edge>(lookup => lookup
                            .IncludeAssembliesOfBaseTypes())
                        .ConfigureElements(em => em
                            .UseLowerCaseLabels())
                        //For CosmosDB, we exclude the 'PartitionKey' property from being included in updates.
                        .ConfigureProperties(model => model
                            .ConfigureElement<Vertex>(conf => conf
                                .IgnoreOnUpdate(x => x.partitionKey))))
                    //Disable query logging for a noise free console output.
                    //Enable logging by setting the verbosity to anything but None.
                    .ConfigureOptions(options => options
                        .SetValue(WebSocketGremlinqOptions.QueryLogLogLevel, LogLevel.None))

                    .UseCosmosDb(builder => builder
                        .At(new Uri(Configuration["Cosmos:Account"]), Configuration["Cosmos:DatabaseName"], Configuration["Cosmos:GraphName"])
                        .AuthenticateBy(Configuration["Cosmos:Key"])
                        .ConfigureWebSocket(_ => _
                            .ConfigureGremlinClient(client => client
                                .ObserveResultStatusAttributes((requestMessage, statusAttributes) =>
                                {
                                    if (statusAttributes.TryGetValue("x-ms-total-request-charge", out var requestCharge))
                                        env.Logger.LogInformation($"Query {requestMessage.RequestId} had a RU charge of {requestCharge}.");
                                }))))));
```

**Comment by danielcweber** [comment]
>I am seeing this same error on some queries but not others

That's where I'm supposed to ask "what error", so....what error ? ;-)

**Comment by danielcweber** [comment]
>services.AddGremlinq(a => new GremlinqSetup(services)
 
That's an odd thing to do, though probably correct. What's the rationale for this?

**Comment by danielcweber** [comment]
>@danielcweber I am seeing this same error on some queries but not others

Does it look the same as the one at the top? Please still post the exact error. Did you log the raw gremlin query and verify that it should indeed yield a result? What version of Gremlinq are you using?

**Comment by jonathaneckman** [comment]
@danielcweber sorry, yes. The error was "Source sequence doesn't contain any elements". Your questions gave me the clue I needed. Results weren't being returned as expected but it was a namespace/serialization issue on my end botching a refactor. Thanks for the help.
