### ISSUE TITLE
No double quotes in Janusgraph response?

### ISSUE THREAD

**Issue by dave93cab** [ExRam/ExRam.Gremlinq#96]
Trying to run your sample app against a janusgraph install and getting this error

`fail: Queries[0]
      Error executing Gremlin query {"RequestId":"79f70dc1-85d4-4e07-b4be-f7cc7c0d5ca7","Operation":"bytecode","Processor":"traversal","Arguments":{"gremlin":{"SourceInstructions":[],"StepInstructions":[{"OperatorName":"addV"
,"Arguments":["Person"]},{"OperatorName":"property","Arguments":[{"EnumName":"Cardinality","EnumValue":"single"},"Age",29]},{"OperatorName":"property","Arguments":[{"EnumName":"Cardinality","EnumValue":"single"},"Name","Marko
"]},{"OperatorName":"property","Arguments":[{"EnumName":"Cardinality","EnumValue":"single"},"PartitionKey","PartitionKey"]},{"OperatorName":"limit","Arguments":[1]},{"OperatorName":"project","Arguments":["id","label","propert
ies"]},{"OperatorName":"by","Arguments":[{"EnumName":"T","EnumValue":"id"}]},{"OperatorName":"by","Arguments":[{"EnumName":"T","EnumValue":"label"}]},{"OperatorName":"by","Arguments":[{"SourceInstructions":[],"StepInstruction
s":[{"OperatorName":"properties","Arguments":[]},{"OperatorName":"group","Arguments":[]},{"OperatorName":"by","Arguments":[{"EnumName":"T","EnumValue":"label"}]},{"OperatorName":"by","Arguments":[{"SourceInstructions":[],"Ste
pInstructions":[{"OperatorName":"project","Arguments":["id","label","value","properties"]},{"OperatorName":"by","Arguments":[{"EnumName":"T","EnumValue":"id"}]},{"OperatorName":"by","Arguments":[{"EnumName":"T","EnumValue":"l
abel"}]},{"OperatorName":"by","Arguments":[{"EnumName":"T","EnumValue":"value"}]},{"OperatorName":"by","Arguments":[{"SourceInstructions":[],"StepInstructions":[{"OperatorName":"valueMap","Arguments":[]}]}]},{"OperatorName":"
fold","Arguments":[]}]}]}]}]}]},"aliases":{"g":"g"}}}:
      Gremlin.Net.Driver.Exceptions.ResponseException: ServerError: Could not deserialize the JSON value as required. Nested exception: org.apache.tinkerpop.shaded.jackson.core.JsonParseException: Unexpected character ('@' (c
ode 64)): was expecting double-quote to start field name
 at [Source: {@type=g:Bytecode, @value={step=[[addV, Person], [property, {@type=g:Cardinality, @value=single}, Age, {@type=g:Int32, @value=29}], [property, {@type=g:Cardinality, @value=single}, Name, Marko], [property, {@type
=g:Cardinality, @value=single}, PartitionKey, PartitionKey], [limit, {@type=g:Int64, @value=1}], [project, id, label, properties], [by, {@type=g:T, @value=id}], [by, {@type=g:T, @value=label}], [by, {@type=g:Bytecode, @value=
{step=[[properties], [group], [by, {@type=g:T, @value=label}], [by, {@type=g:Bytecode, @value={step=[[project, id, label, value, properties], [by, {@type=g:T, @value=id}], [by, {@type=g:T, @value=label}], [by, {@type=g:T, @va
lue=value}], [by, {@type=g:Bytecode, @value={step=[[valueMap]]}}], [fold]]}}]]}}]]}}; line: 1, column: 3]
 at [Source: {@type=g:Bytecode, @value={step=[[addV, Person], [property, {@type=g:Cardinality, @value=single}, Age, {@type=g:Int32, @value=29}], [property, {@type=g:Cardinality, @value=single}, Name, Marko], [property, {@type
=g:Cardinality, @value=single}, PartitionKey, PartitionKey], [limit, {@type=g:Int64, @value=1}], [project, id, label, properties], [by, {@type=g:T, @value=id}], [by, {@type=g:T, @value=label}], [by, {@type=g:Bytecode, @value=
{step=[[properties], [group], [by, {@type=g:T, @value=label}], [by, {@type=g:Bytecode, @value={step=[[project, id, label, value, properties], [by, {@type=g:T, @value=id}], [by, {@type=g:T, @value=label}], [by, {@type=g:T, @va
lue=value}], [by, {@type=g:Bytecode, @value={step=[[valueMap]]}}], [fold]]}}]]}}]]}}; line: 1, column: 1]
         at Gremlin.Net.Driver.Messages.ResponseStatusExtensions.ThrowIfStatusIndicatesError(ResponseStatus status)
         at Gremlin.Net.Driver.Connection.TryParseResponseMessage(ResponseMessage`1 receivedMsg)
         at Gremlin.Net.Driver.Connection.Parse(Byte[] received)
      --- End of stack trace from previous location where exception was thrown ---
         at Gremlin.Net.Driver.ProxyConnection.SubmitAsync[T](RequestMessage requestMessage)
         at Gremlin.Net.Driver.GremlinClient.SubmitAsync[T](RequestMessage requestMessage)
         at ExRam.Gremlinq.Core.GremlinQueryEnvironmentExtensions.WebSocketGremlinQueryExecutor.<>c__DisplayClass6_0.<<Execute>g__Core|0>d.MoveNext() in /home/runner/work/ExRam.Gremlinq/ExRam.Gremlinq/ExRam.Gremlinq.Providers
.WebSocket/GremlinQueryEnvironmentExtensions.cs:line 91
`

looks like it is expecting the graphson results to be double quoted `"@type"` etc but my response is not in that format it is with equals signs `@type=`. Any pointers?

**Comment by dave93cab** [comment]
Seems it is because i was missing the /gremlin, but with that I get `System.Net.WebSockets.WebSocketException: Unable to connect to the remote server ---> System.Net.Http.HttpRequestException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.`

I can connect using that Uri with other tools ws://server_ip:8182/gremlin
